name: distance
description: Distance Flame Game

dependencies:
  screen:
  flutter:
    sdk: flutter
  flame: ^0.18.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/icons8-neutral.png
    - assets/images/icons8-sad.png
    - assets/images/icons8-neutral-yellow.png

   